name: run-cron

on:
  schedule:
    - cron: '0 21 * * *' # Ejecuta el cron todos los días a 21:00 UTC
  workflow_dispatch: # Permite ejecutarlo manualmente desde la interfaz de GitHub

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  AUTHORIZED_CLIENT: ${{ secrets.AUTHORIZED_CLIENT }}
  CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
  PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  SHEET_ID: ${{ secrets.SHEET_ID }}

jobs:
  run-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '^3.13' # Especifica la versión de Python que usas

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Create credentials file
        run: echo "${{ secrets.GSPREAD_CREDENTIALS_FILE }}" > credentials.json

      - name: Run your script
        run: poetry run python ./src/main.py
